server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #USER-SERVICE
        - id: user-service-info
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: user-service-shipping-info
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/profiles/**

        #IDENTITY-SERVICE
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        #PRODUCT-SERVICE
        - id: product-service-product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**
        - id: product-service-category
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/categories/**
        - id: product-service-brand
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/brands/**

        # OPENAPI DOCS ROUTE
        - id: openapi
          filters:
            - RewritePath=/v3/api-docs/(?<segment>.*), /${segment}/v3/api-docs
          predicates:
            - Path=/v3/api-docs/**
          uri: http://localhost:${server.port}

springdoc:
  swagger-ui:
    urls:
      - name: Identity Service APIs
        url: /v3/api-docs/identity
      - name: Media Service APIs
        url: /v3/api-docs/medias
      - name: User Service APIs
        url: /v3/api-docs/users
      - name: Product Service APIs
        url: /v3/api-docs/products
