server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: identity-service
          uri: lb:http://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**