server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        #IDENTITY-SERVICE
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /v3/api-docs/identity-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #PRODUCT-SERVICE
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**, /api/v1/brands/**, /v3/api-docs/product-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #USER-SERVICE
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**, /api/v1/profiles/**, /v3/api-docs/user-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #MEDIA-SERVICE
        - id: media-service
          uri: lb://MEDIA-SERVICE
          predicates:
            - Path=/api/v1/medias/**, /v3/api-docs/media-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #MAIL-SERVICE
        - id: mail-service
          uri: lb://MAIL-SERVICE
          predicates:
            - Path=/api/v1/mail/**, /v3/api-docs/mail-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #INVENTORY-SERVICE
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**, /v3/api-docs/inventory-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #CART-SERVICE
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**, /v3/api-docs/cart-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #ORDER-SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**, /v3/api-docs/order-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        #PAYMENT-SERVICE
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**, /v3/api-docs/payment-service
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /v3/api-docs/identity-service
        name: Identity Service
      - url: /v3/api-docs/product-service
        name: Product Service
      - url: /v3/api-docs/user-service
        name: User Service
      - url: /v3/api-docs/media-service
        name: Media Service
      - url: /v3/api-docs/mail-service
        name: Mail Service
      - url: /v3/api-docs/inventory-service
        name: Inventory Service
      - url: /v3/api-docs/cart-service
        name: Cart Service
      - url: /v3/api-docs/order-service
        name: Order Service
      - url: /v3/api-docs/payment-service
        name: Payment Service