server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/user_service}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:25092004chien}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      show_sql: true
      properties:
        hibernate.format_sql: true

