server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #USER-SERVICE
        - id: user-service-info
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: user-service-shipping-info
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/profiles/**

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/v1/auth/**
