server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/media_service
    username: root
    password: 25092004chien
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

openapi:
  service:
    api-docs: media-service
    server: http://localhost:8086
    title: Media service
    version: 1.0.0
