server:
  port: 8091
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: order_db
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      orderCreated: order-created-topic
      orderUpdated: order-updated-topic
      orderMail: order-mail-topic
openapi:
  service:
    api-docs: order-service
    server: http://localhost:8091
    title: Order service
    version: 1.0.0
