server:
  port: 8092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service
    username: root
    password: 25092004chien
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:29092
    topic:
      checkoutOrder: checkout-order-topic

payment:
  vnpay:
    url: ${vnp_Url}
    tmnCode: ${vnp_TmnCode}
    hashSecret: ${vnp_HashSecret}
    returnUrl: ${vnp_Url_Return}


openapi:
  service:
    api-docs: payment-service
    server: http://localhost:8092
    title: Payment service
    version: 1.0.0
