server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_service
    username: root
    password: 25092004chien
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

openapi:
  service:
    api-docs: product-service
    server: http://localhost:8085
    title: Product service
    version: 1.0.0
