server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 25092004chien
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

openapi:
  service:
    api-docs: user-service
    server: http://localhost:8082
    title: User service
    version: 1.0.0
