server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
  application:
    name: config-server

  jpa:
    properties:
      hibernate:
        ejb:
          interceptor=com:
            example: MyCustomInterceptor